### PR TITLE
#25 - Add target resources to destroy

### PR DESCRIPTION
**Pull request by kingsleyadam**
Including adjusting destroy test

### CODE REVIEW

**Review by nmaludy — COMMENTED** [review]
What happens if target_resources is not specified?

**Comment by kingsleyadam** [comment]
> What happens if target_resources is not specified?

If it's either an [empty list](https://github.com/beelit94/python-terraform/blob/master/python_terraform/__init__.py#L214) or a [None type](https://github.com/beelit94/python-terraform/blob/master/python_terraform/__init__.py#L236) it won't apply any resource targeting and all resources will be destroyed (the default behavior).

**Comment by kingsleyadam** [comment]
I also realized I didn't add a change log or version bump. I'll get that added.

**Review by nmaludy — CHANGES_REQUESTED** [review]
Awesome! think we just need a changeling and version bump and this is good to merge in!

Thanks again for all your work on this pack, it's very much appreciated!

**Comment by punkrokk** [comment]
Should we be nice and add a reminder in case someone might not realize that? 

JP Bourget / @punkrokk

**Comment by nmaludy** [comment]
JP that's a great idea! We should probably add a build check for that so the user is reminded without needing a review from a maintainer. This would make more PRs immediately mergeable!

**Comment by arm4b** [comment]
I was looking at https://github.com/marketplace/actions/changelog-reminder before in order to solve this repetitive problem.
It also has all the functionality we'll need to be integrated into different repos is it stackstorm-exchange or stackstorm/st2 via https://github.com/peterjgrainger/action-changelog-reminder/issues/2.

The only problem is adding it for every repo.
@nmaludy interested in automating adding this integration for every exchange repo?

**Comment by punkrokk** [comment]
Well,

For historical purposes, it was an exchange exactly like this which ended up in a cross country bike ride for me: http://cycleoverride.org/about-us/

Anyways - what I really meant was in regards to terraform - If there was an empty list in the action that would cause a destroy - potentially unintended, it would be nice to put a nice fat warning in the top of the read me with a “you might destroy your infrastructure by mistake”.

+2 on the change log checker. I have a script that can update every repo in like 2 min. Just get me the diff. 

JP Bourget / @punkrokk

**Comment by kingsleyadam** [comment]
> Anyways - what I really meant was in regards to terraform - If there was an empty list in the action that would cause a destroy - potentially unintended, it would be nice to put a nice fat warning in the top of the read me with a “you might destroy your infrastructure by mistake”.

@punkrokk We can add something to the description of the action?

> Destroy the Terraform managed infrastructure. Reminder, if you do NOT specify target_resources this will delete your entire managed infrastructure.

**Comment by punkrokk** [comment]
Yes, please

**Review by nmaludy — APPROVED** [review]

**Pull request merged**
