### PR TITLE
Add more options for plan and apply

### PR DESCRIPTION
**Pull request by jschoewe**
Added more variables and options from the python terraform module to give the stackstorm actions more functionality. These new variables will allow you to specify a state file, specify target resources, and pass variables without needing a file.

Also, it isn't necessary to import the os module and change directory if you pass the path into the terraform function.

### CODE REVIEW

**Review by nmaludy — CHANGES_REQUESTED** [review]
Need a changelog entry and unit tests.

**Review by nmaludy — APPROVED** [review]
:+1:

**Review by nmaludy — APPROVED** [review]
Looks good from my end!

**Comment by blag** [comment]
Thanks!

**Pull request merged**
