### PR TITLE
1.1.1 - Bugfix for invalid output variable.

### PR DESCRIPTION
**Pull request by lorddaren**

### CODE REVIEW

**Comment by lorddaren** [comment]
@nmaludy  Can you merge this when you get a minute.

**Comment by Tylerlhess** [comment]
+1 as I was just submitting this myself.

**Comment by arm4b** [comment]
@bishopbm1, this needs a review from @StackStorm-Exchange/encoretechnologies as a pack maintainer

**Review by bishopbm1 — APPROVED** [review]
LGTM!

**Pull request merged**
